version: "3"
volumes:
  postgres_data:
  nginx_conf:
  media:
  static:
services:
  db:
    image: postgres:12.4
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    env_file:
        - ./.env
  web:
    image: toshiharu13/web_for_diplom
    restart: always
    depends_on:
        - db
    env_file:
        - ./.env
    expose:
      - 8000
    volumes:
      - media:/code/media
      - static:/code/static
  nginx:
    image: nginx:1.19.3
    restart: always
    depends_on:
      - web
    volumes:
        - static:/var/html/static/
        - media:/var/html/media/
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
        - "80:80"