# Generated by Django 3.2.3 on 2021-06-01 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingridient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', models.PositiveSmallIntegerField(default=1, verbose_name='Оценка')),
            ],
        ),
        migrations.CreateModel(
            name='ListOfIngridients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('units_of_measurement', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='prod_h/')),
                ('text', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('ingridients', models.ManyToManyField(to='prod_h.Ingridient')),
                ('teg', models.ManyToManyField(to='prod_h.Teg')),
            ],
        ),
        migrations.AddField(
            model_name='ingridient',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingridient_name', to='prod_h.listofingridients'),
        ),
        migrations.AddField(
            model_name='ingridient',
            name='units_of_measurement',
            field=models.ManyToManyField(to='prod_h.ListOfIngridients'),
        ),
    ]
