# Generated by Django 3.2.3 on 2021-06-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_h', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teg',
            name='color',
            field=models.CharField(blank=True, max_length=20, verbose_name='Цвет тега'),
        ),
    ]
