# Generated by Django 3.2.3 on 2021-06-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_h', '0002_teg_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofingridients',
            name='name',
            field=models.CharField(help_text='Название ингредиента, макc. 50 символов', max_length=50, unique=True, verbose_name='Название ингредиента'),
        ),
        migrations.AlterField(
            model_name='listofingridients',
            name='units_of_measurement',
            field=models.CharField(help_text='Макс. 20 симоволов', max_length=20, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.PositiveSmallIntegerField(verbose_name='Вермя приготовления'),
        ),
    ]
