# Generated by Django 3.2.3 on 2021-06-16 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod_h', '0002_auto_20210615_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='teg',
            new_name='tags',
        ),
    ]
