# Generated by Django 3.2.3 on 2021-06-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod_h', '0003_rename_teg_recipe_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingridient',
            new_name='Ingredient',
        ),
    ]
