# Generated by Django 3.2.3 on 2021-06-29 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod_h', '0003_auto_20210628_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingridient_names', to='prod_h.listofingridients'),
        ),
    ]
