# Generated by Django 3.2.3 on 2021-06-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_h', '0004_rename_ingridient_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='teg',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
