# Generated by Django 3.2.3 on 2021-06-29 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod_h', '0004_alter_amount_ingredient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teg',
            new_name='Tag',
        ),
    ]
