# Generated by Django 3.2.3 on 2021-06-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_h', '0005_teg_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teg',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
