# Generated by Django 3.2.3 on 2021-06-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod_h', '0006_alter_teg_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingridients',
            new_name='ingredients',
        ),
    ]
