# Generated by Django 3.2.3 on 2021-06-29 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prod_h', '0007_alter_recipe_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amount',
            options={'verbose_name': 'Ингридиент для рецепта', 'verbose_name_plural': 'Ингридиенты для рецепта'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписка'},
        ),
        migrations.AlterModelOptions(
            name='listofingridients',
            options={'verbose_name': 'Ингридиент для цецепта', 'verbose_name_plural': 'Ингридиенты для цецепта'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='В чью корзину положен рецепт'),
        ),
    ]
