# Generated by Django 3.2.3 on 2021-06-29 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod_h', '0008_auto_20210629_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listofingridients',
            options={'verbose_name': 'Список продуктов', 'verbose_name_plural': 'Список продуктов'},
        ),
    ]
